# This is a basic workflow to help you get started with Actions

name: Increment Semver

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Unity Automated Semver
        # You may pin to the exact commit or the version.
        # uses: AlexHolderDeveloper/UnityAutomatedSemver@4ae3f01af014984baf49ed49917f5c2cecb2948e
        uses: AlexHolderDeveloper/UnityAutomatedSemver@v1.0.1
        with:
          # Which number to increment based on semver rules.
          semver-update-type: patch # default is patch
